### ISSUE TITLE
UnhandledPromiseRejectionWarning when database does not exist

### ISSUE THREAD

**Issue by sylver** [materya/quartz#4]
```
> migrate up

(node:16) UnhandledPromiseRejectionWarning: ConnectionError: database "foobar" does not exist
    at createConnection (/app/node_modules/slonik/dist/factories/createConnection.js:69:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async main (/app/node_modules/@materya/quartz/dist/bin/migrate.js:108:5)
```

**Comment by sylver** [comment]
Same issue if any migration/seed throws an error as an async function.
